config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  root to: 'services#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :services, only: [:index, :new, :create, :show, :edit, :update] do
    collection do
      get 'search', to: 'services#search'
    end
    resources :bookings, only: [:new, :create]
  end

  get 'dashboard', to: 'pages#dashboard'
  resources :bookings, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :postcode, presence: true, length: { in: 5..7 }
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :bookings

  geocoded_by :postcode
  after_validation :geocode, if: :postcode_changed?
  validates :postcode, :title, :description, presence: true
  validates :category, presence: true, inclusion: { in: %w(walking sitting grooming) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :photo, PhotoUploader
  has_many :bookings
  has_many :services

  validates :email, presence: true, format: { with: /\A.*@.*\.*\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :set_empty_service

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def set_empty_service
    @service = Service.new
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
    @service = Service.find(params[:service_id])
    authorize(@booking)
  end

  def show
  end

  def create
    @service = Service.find(params[:service_id])
    @booking = Booking.new(booking_params)
    @booking.service = @service
    @booking.user = current_user
    authorize(@booking)
    if @booking.save
      redirect_to service_path(@service)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to service_booking_path(@booking)
    else
      render :edit
    end
  end

  def search
    # @bookings = Booking.where(category: params[:category])
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:date, :category, :postcode, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def bookings

  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  # protected
  #   def after_sign_up_path_for(resource)
  #     signed_in_dashboard_services_path(resource)
  #   end

  #   def after_update_path_for(resource)
  #     signed_in_dashboard_services_path(resource)
  #   end

  private
  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :photo, :photo_cache, :first_name, :last_name)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :photo, :photo_cache, :current_password, :first_name, :last_name)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :find_service, only: [ :show, :edit, :update, :destroy ]
  skip_before_action :authenticate_user!, only: [ :index, :show, :search ]

  def index
    @services = policy_scope(Service)
  end

  def new
    @service = Service.new
    authorize(@service)
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user
    authorize(@service)
    if @service.save
      redirect_to service_path(@service)
    else
      render "new"
    end
  end

  def show
    @service = find_service
    authorize(@service)
  end

  def edit
    @service = find_service
    authorize(@service)
  end

  def update
    authorize(@service)
    if @service.update(service_params)
      redirect_to service_path(@service)
    else
      render "edit"
    end
  end

  def destroy
     @service.destroy
     authorize(@service)
     redirect_to services_path(@service)
  end

  def search
    if params[:category] && params[:postcode]
      postcode = params[:postcode]
      query = "category = '#{params[:category]}'"
    elsif params[:category].nil?
      postcode = params[:postcode]
      query = "category = 'walking' OR (category = 'brooming') OR (category = 'sitting')"
    else
      postcode = "WC2N 5DU" # london postcode
      query = "category = '#{params[:category]}'"
    end
    @services = Service.near(postcode, 7).where(query)
    authorize(@services)
     @hash = Gmaps4rails.build_markers(@services) do |service, marker|
      marker.lat service.latitude
      marker.lng service.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def seach_by_category
    @services = Service.where(category: params[:category])
  end

  private

  def find_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:title, :category, :description, :postcode, :cost)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h1>Create Booking</h1>

<div class="container">
    <%= simple_form_for [@service, @booking] do |f| %>
      <%= f.input :date %>
      <%= f.input :category, prompt: [ "Sitting" ], collection: [ "Sitting", "Walking", "Grooming"] %>
      <%= f.input :postcode %>
      <%= f.submit "Create Booking" %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PetBoom!</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  </head>
  <body>

    <%= render 'shared/nav' %>

    <div class="notices-container">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="page">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

   <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "application" %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= yield(:after_js) %>

        <script>
      // Nav menu toggle
$("#menu-trigger").click(function(){
    $("#nav-menu").fadeToggle();
});

//model open
$("#open-create").click(function(){
  var scrollTop = window.scrollY;
  $('#model-cover').css('top', scrollTop + "px");
  $('#model-cover').fadeToggle();
  $('body').css('overflow', 'hidden');
});

$("#model-close").click(function(){
  $('#model-cover').fadeToggle();
  $('body').css('overflow', 'scroll');
});

    </script>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="profile">
  <div class="">
   <%= cl_image_tag current_user.photo, height: 250, width: 250, crop: :fill, class: "profile-photo"%>
   <h2><%= current_user.first_name %> <%= current_user.last_name %></h2>

   <%= link_to 'edit', edit_user_registration_path, class: "btn btn-primary dash" %>

   </div>
  </div>



<div class="dashboard-container">
     <div class="left">
       <h2>Your services</h2>
       <% current_user.services.each do |service| %>
         <%= service.category %><br>
           <%= service.description %>

       <h2><%= current_user.address %></h2>
      <% end %>
     </div>
     <div class="right">
      <h2>Pending Bookings</h2>

        <% current_user.services.each do |service| %>
          <% service.bookings.each do |booking| %>
            <%= booking.category %> / <%= booking.status %>
          <% end %>
        <% end %>


     </div>
</div>

app/views/services/edit.html.erb
<div class="form-template-container">
  <div class="form-template-content">
    <div class="form-template-center">
      <%= render 'shared/service_form' %>
    </div>
  </div>
  <div class="form-template-banner" style="background-image: url('https://images.unsplash.com/photo-1502673530728-f79b4cab31b1?auto=format&fit=crop&w=2250&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D');">

  </div>
</div>

app/views/services/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1494947665470-20322015e3a8?auto=format&fit=crop&w=2600&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D');">
  <div class="banner-content">
    <span class="slide-down">
      <h1>Pet Boom</h1>
      <h3>Find the right sitter for your pet!</h3>
    </span>
    <form action="services/search">
      <div class="search-fade form-group form-inline">
        <input type="text" name="postcode" placeholder="What's your postcode?" class="form-control width-600">
        <button type="submit" class="form-control btn btn-primary">Boom!</button>
      </div>
    </form>
    </div>
  <a href="#index" class="to-content">
    <i class="fa fa-arrow-down" aria-hidden="true"></i>
  </a>
</div>

<div class="container-white" id="index">
  <div class="cards">
    <%= render "/shared/service_card" %>
  </div>
</div>

<%= content_for(:after_js) do %>
<script>
  function initUpdateNavbarOnScroll() {
  const navbar = document.getElementById('navbar');
  const btn = document.getElementById('login-btn');
  const logo = document.getElementById('logo-text');
  const icons = document.querySelectorAll('.icon-navbar');
  const iconsText = document.querySelectorAll('.icon-text');

//changing button and text on navbar color to blue when scroolling
  window.addEventListener('scroll', (event) => {
    if (window.scrollY >= window.innerHeight) {
      navbar.classList.remove('transparent-nav');
      logo.classList.remove('white-logo');
      icons.forEach((icon) => {
        icon.classList.add('icon-path-blue');
      });
      iconsText.forEach((text) => {
        text.classList.add('icon-text-blue');
      });
      if (btn) {
        btn.classList.add("btn-to-blue");
      }
    } else {
      navbar.classList.add('transparent-nav');
      logo.classList.add('white-logo');
      icons.forEach((icon) => {
        icon.classList.remove('icon-path-blue');
      });
      iconsText.forEach((text) => {
        text.classList.remove('icon-text-blue');
      });
      if (btn) {
        btn.classList.remove('btn-to-blue');
      }
    }
  });
}

initUpdateNavbarOnScroll()
</script>
<% end %>

app/views/services/new.html.erb
<div class="form-template-container">
  <div class="form-template-content">
    <div class="form-template-center">
        <%= render 'shared/service_form' %>
    </div>
  </div>
  <div class="form-template-banner" style="background-image: url('https://images.unsplash.com/photo-1496661269814-a841e78df103?auto=format&fit=crop&w=3300&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D');">

  </div>
</div>

app/views/services/show.html.erb
<% usernames = %w(andrew cris nathalie nati david joe lenny alex sandrine arthur joyce lucas mansoor romain sam andy) %>

<% reviews = ["This is a new review of the service", "This is also a review of the service!", "Guess what? Yeh, a review of the service.", "Service review.", "This is my review of this service.", "Just poting a review, of what? he service. Nice.", "Just reviewing this service.", "I used this serviced and here is a review of said service", "I was paid $5 to write 10,000 reviews of this product."] %>

<% star1 = '<i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>' %>

<% star2 = '<i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>' %>

<% star3 = '<i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>' %>

<% star4 = '<i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star" aria-hidden="true"></i>' %>

<% star5 = '<i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star filled" aria-hidden="true"></i>
            <i class="fa fa-star filled" aria-hidden="true"></i>' %>

<% ratings = [star1, star2, star3, star4, star5] %>

<div class="service-container">
  <div class="service-user-column">
    <%= cl_image_tag @service.user.photo, height: 280, width: 280, crop: :fill, class: "service-avatar" %>
              <span class="tag-container" style="position:absolute; top:260px; left:200px; margin: 0 auto;">
              <div class="tag-point">
                <div class="tag-hole"></div>
              </div><div class="tag-box">£<%= @service.cost.round %>/h</div>
            </span>

    <p class="service-name"><%= @service.user.first_name %> <%= @service.user.last_name %></p>
    <% if current_user != @service.user %>
      <%= link_to "Book", new_service_booking_path(@service), class:"btn-book-service" %>
    <% end %>
    <!-- edit and delete buttons -->
    <% if policy(@service).edit? %>
      <%= link_to "Edit", edit_service_path(@service), class: "btn btn-primary btn-lg" %>
      <%= link_to "delete", service_path(@service), method: :delete, data: {confirm: "are you sure?"}, class: "btn btn-primary btn-lg" %>
    <% end %>
    <p class="service-title"><%= @service.title %></p>
    <p class="service-description"><%= @service.description %></p>

  </div>
  <div class="service-right">
    <div class="rating-container">
      <h1>Rating overview</h1>
      <div class="rating-row">
        <div class="rating-stars">
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star filled" aria-hidden="true"></i>
        </div>
        <div class="rating-bars">
          <div class="rating-highlight" style="width:<%= (60..90).to_a.sample %>%"></div>
        </div>
      </div>
      <div class="rating-row">
        <div class="rating-stars">
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star" aria-hidden="true"></i>
        </div>
        <div class="rating-bars">
          <div class="rating-highlight" style="width:<%= (60..80).to_a.sample %>%"></div>
        </div>
      </div>
      <div class="rating-row">
        <div class="rating-stars">
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star" aria-hidden="true"></i>
          <i class="fa fa-star" aria-hidden="true"></i>
        </div>
        <div class="rating-bars">
          <div class="rating-highlight" style="width:<%= (33..88).to_a.sample %>%"></div>
        </div>
      </div>
      <div class="rating-row">
        <div class="rating-stars">
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star" aria-hidden="true"></i>
          <i class="fa fa-star" aria-hidden="true"></i>
          <i class="fa fa-star" aria-hidden="true"></i>
        </div>
        <div class="rating-bars">
          <div class="rating-highlight" style="width:<%= (10..45).to_a.sample %>%"></div>
        </div>
      </div>
      <div class="rating-row">
        <div class="rating-stars">
          <i class="fa fa-star filled" aria-hidden="true"></i>
          <i class="fa fa-star" aria-hidden="true"></i>
          <i class="fa fa-star" aria-hidden="true"></i>
          <i class="fa fa-star" aria-hidden="true"></i>
          <i class="fa fa-star" aria-hidden="true"></i>
        </div>
        <div class="rating-bars">
          <div class="rating-highlight" style="width:<%= (5..60).to_a.sample %>%"></div>
        </div>
      </div>
    </div>
    <div class="service-reviews-container">
    <h1>Reviews</h1>
      <!-- start review -->
      <div class="review-container">
        <div class="review-details">
          <!-- reviewers avatar -->
          <%= cl_image_tag @service.user.photo, height: 40, width: 40, crop: :fill, class: "review-avatar" %>
          <!-- reviewers name -->
          <p class="review-username"><%= usernames.sample %></p>
          <!-- reviewer rating stars -->
          <div class="review-stars-container">
            <%= ratings.sample.html_safe %>
          </div>
        </div>
        <div class="review-up-arrow"></div>
        <div class="review-content">
          <div class="review-bubble">
              <!-- the review content -->
              <%= reviews.sample %>
          </div>
        </div>
      </div>
      <!-- end review -->

      <!-- start review -->
      <div class="review-container">
        <div class="review-details">
          <!-- reviewers avatar -->
          <%= cl_image_tag @service.user.photo, height: 40, width: 40, crop: :fill, class: "review-avatar" %>
          <!-- reviewers name -->
          <p class="review-username"><%= usernames.sample %></p>
          <!-- reviewer rating stars -->
          <div class="review-stars-container">
            <%= ratings.sample.html_safe %>
          </div>
        </div>
        <div class="review-up-arrow"></div>
        <div class="review-content">
          <div class="review-bubble">
              <!-- the review content -->
            <%= reviews.sample %>
          </div>
        </div>
      </div>
      <!-- end review -->

      <!-- start review -->
      <div class="review-container">
        <div class="review-details">
          <!-- reviewers avatar -->
          <%= cl_image_tag @service.user.photo, height: 40, width: 40, crop: :fill, class: "review-avatar" %>
          <!-- reviewers name -->
          <p class="review-username"><%= usernames.sample %></p>
          <!-- reviewer rating stars -->
          <div class="review-stars-container">
            <%= ratings.sample.html_safe %>
          </div>
        </div>
        <div class="review-up-arrow"></div>
        <div class="review-content">
          <div class="review-bubble">
              <!-- the review content -->
            <%= reviews.sample %>
          </div>
        </div>
      </div>
      <!-- end review -->

      <!-- start review -->
      <div class="review-container">
        <div class="review-details">
          <!-- reviewers avatar -->
          <%= cl_image_tag @service.user.photo, height: 40, width: 40, crop: :fill, class: "review-avatar" %>
          <!-- reviewers name -->
          <p class="review-username"><%= usernames.sample %></p>
          <!-- reviewer rating stars -->
          <div class="review-stars-container">
            <%= ratings.sample.html_safe %>
          </div>
        </div>
        <div class="review-up-arrow"></div>
        <div class="review-content">
          <div class="review-bubble">
              <!-- the review content -->
            <%= reviews.sample %>
          </div>
        </div>
      </div>
      <!-- end review -->

      <!-- start review -->
      <div class="review-container">
        <div class="review-details">
          <!-- reviewers avatar -->
          <%= cl_image_tag @service.user.photo, height: 40, width: 40, crop: :fill, class: "review-avatar" %>
          <!-- reviewers name -->
          <p class="review-username"><%= usernames.sample %></p>
          <!-- reviewer rating stars -->
          <div class="review-stars-container">
            <%= ratings.sample.html_safe %>
          </div>
        </div>
        <div class="review-up-arrow"></div>
        <div class="review-content">
          <div class="review-bubble">
              <!-- the review content -->
            <%= reviews.sample %>
          </div>
        </div>
      </div>
      <!-- end review -->

      <!-- start review -->
      <div class="review-container">
        <div class="review-details">
          <!-- reviewers avatar -->
          <%= cl_image_tag @service.user.photo, height: 40, width: 40, crop: :fill, class: "review-avatar" %>
          <!-- reviewers name -->
          <p class="review-username"><%= usernames.sample %></p>
          <!-- reviewer rating stars -->
          <div class="review-stars-container">
             <%= ratings.sample.html_safe %>
          </div>
        </div>
        <div class="review-up-arrow"></div>
        <div class="review-content">
          <div class="review-bubble">
              <!-- the review content -->
            <%= reviews.sample %>
          </div>
        </div>
      </div>
      <!-- end review -->
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="text-center">
  PetBoom! made in London.
</footer>